refactor: switch back to build fex-emu from source

diff --git a/.github/workflows/update_tagged_versions.yml b/.github/workflows/update_tagged_versions.yml
--- a/.github/workflows/update_tagged_versions.yml
+++ b/.github/workflows/update_tagged_versions.yml
@@ -47,6 +47,41 @@ jobs:
             echo "updated=false" >> $GITHUB_OUTPUT
           fi
 
+      - name: Find latest tag (update fex-emu)
+        id: update_fex-emu_find_latest
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REPOSITORY: FEX-Emu/FEX
+        run: |
+          if ! LATEST_TAG=$(gh api repos/$REPOSITORY/releases/latest --jq '.tag_name' 2>/dev/null); then
+            echo "::error::Failed to fetch latest tag for repository $REPOSITORY"
+          elif [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then
+            echo "::warning::No tags found for repository $REPOSITORY"
+          else
+            echo "::notice::Latest tag for repository $REPOSITORY: $LATEST_TAG"
+          fi
+          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
+      - name: update fex-emu
+        id: update_fex-emu
+        run: |
+          LATEST_TAG=${{ steps.update_fex-emu_find_latest.outputs.tag }}
+
+          echo "FEX_VER: $LATEST_TAG"
+
+          [ -n "$LATEST_TAG" ] && [ "$LATEST_TAG" != "null" ] && echo 'patching Dockerfile' && sed -i "s|ARG FEX_VER=.*|ARG FEX_VER=${LATEST_TAG}|g" $GITHUB_WORKSPACE/Dockerfile
+
+          # Commit FEX-EMU changes if any
+          git add .
+          git status
+          git config --local user.name ${{ env.GIT_USER }}
+          git config --local user.email ${{ env.GIT_EMAIL }}
+          if ! git diff --cached --quiet; then
+            git commit -m "feat: Update FEX-EMU version to ${LATEST_TAG}"
+            echo "updated=true" >> $GITHUB_OUTPUT
+          else
+            echo "updated=false" >> $GITHUB_OUTPUT
+          fi
+
       - name: update resources
         id: update_resources
         env:
@@ -78,7 +113,7 @@ jobs:
           git push origin $GITHUB_REF_NAME
 
       - name: trigger build workflow
-        if: steps.update_fivem.outputs.updated == 'true' || steps.update_resources.outputs.updated == 'true'
+        if: steps.update_fivem.outputs.updated == 'true' || steps.update_fex-emu.outputs.updated == 'true' || steps.update_resources.outputs.updated == 'true'
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
